package exporter

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/ldaidone/go-graphed/internal/ir"
)

// reportTopCoupled caps the "Most Coupled Documents" table so the report
// stays scannable; hubs get their own complete table above it.
const reportTopCoupled = 25

// reportMemberPreview caps the member paths listed per cluster row.
const reportMemberPreview = 8

// Report writes a human-readable markdown summary of the graph to output,
// mirroring the kg metrics and kg clusters views so the terminal report and
// the committed artifact agree. Creating the output directory mirrors the
// guarantee JSON() and HTML() give callers.
func Report(graph ir.Graph, output string) error {
	dir := filepath.Dir(output)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	if err := os.WriteFile(output, []byte(buildMarkdownReport(&graph)), 0644); err != nil {
		return fmt.Errorf("failed to write report file to %s: %w", output, err)
	}
	return nil
}

// docRow is a document with its centrality scores, used for sorting and
// rendering. Scores degrade to zero for snapshots built before the metrics
// pass existed; the is_hub metadata flag still surfaces hubs in that case.
type docRow struct {
	Path     string
	Degree   int
	Weighted float64
	PageRank float64
	IsHub    bool
}

// docRows flattens Graph.Metrics.Documents into a stable row set, falling
// back to the per-document "is_hub" metadata flag when the metrics table is
// missing.
func docRows(graph *ir.Graph) []docRow {
	rows := make([]docRow, 0, len(graph.Documents))
	for path, doc := range graph.Documents {
		row := docRow{Path: path}
		if dm, ok := graph.Metrics.Documents[path]; ok {
			row.Degree = dm.Degree
			row.Weighted = dm.WeightedDegree
			row.PageRank = dm.PageRank
			row.IsHub = dm.IsHub
		}
		if !row.IsHub && doc.Metadata != nil && doc.Metadata[ir.MetadataHubFlag] == "true" {
			row.IsHub = true
		}
		rows = append(rows, row)
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].Path < rows[j].Path })
	return rows
}

// buildMarkdownReport renders the graph as markdown. Output is deterministic
// for a given snapshot: rows sort by score then path, clusters by kind and
// name.
func buildMarkdownReport(graph *ir.Graph) string {
	var sb strings.Builder

	sb.WriteString("# Knowledge Graph Report\n\n")
	sb.WriteString("_Auto-generated by `kg visualize`. Coupling hotspots, hub (\"God Node\") documents, and subsystem clusters at a glance._\n\n")

	// ---- snapshot metadata ----
	sb.WriteString("## Snapshot\n\n")
	if !graph.BuiltAt.IsZero() {
		sb.WriteString(fmt.Sprintf("- **Generated:** %s\n", graph.BuiltAt.UTC().Format(time.RFC3339)))
	}
	sb.WriteString(fmt.Sprintf("- **Documents:** %d\n", len(graph.Documents)))
	sb.WriteString(fmt.Sprintf("- **Links:** %d\n", len(graph.Links)))
	sb.WriteString(fmt.Sprintf("- **Hub (God Node) documents:** %d\n", graph.Metrics.HubCount))

	formatCounts := make(map[string]int)
	for _, d := range graph.Documents {
		formatCounts[d.Format]++
	}
	if len(formatCounts) > 0 {
		formats := make([]string, 0, len(formatCounts))
		for f := range formatCounts {
			formats = append(formats, f)
		}
		sort.Strings(formats)
		parts := make([]string, 0, len(formats))
		for _, f := range formats {
			parts = append(parts, fmt.Sprintf("%s (%d)", f, formatCounts[f]))
		}
		sb.WriteString(fmt.Sprintf("- **Formats:** %s\n", strings.Join(parts, ", ")))
	}

	rows := docRows(graph)

	// ---- hub documents ----
	sb.WriteString("\n## Hub Documents (God Nodes)\n\n")
	sb.WriteString("The most central documents everything funnels through: central DB drivers, middleware, routers. Ranked by PageRank.\n\n")
	hubs := make([]docRow, 0, len(rows))
	for _, r := range rows {
		if r.IsHub {
			hubs = append(hubs, r)
		}
	}
	if len(hubs) == 0 {
		sb.WriteString("_No hub documents flagged in this snapshot. Rebuild with a recent `kg build`._\n\n")
	} else {
		sort.Slice(hubs, func(i, j int) bool {
			if hubs[i].PageRank != hubs[j].PageRank {
				return hubs[i].PageRank > hubs[j].PageRank
			}
			return hubs[i].Path < hubs[j].Path
		})
		sb.WriteString("| Document | Degree | Weighted | PageRank |\n")
		sb.WriteString("| --- | ---: | ---: | ---: |\n")
		for _, r := range hubs {
			sb.WriteString(fmt.Sprintf("| `%s` | %d | %.2f | %.5f |\n", r.Path, r.Degree, r.Weighted, r.PageRank))
		}
	}

	// ---- most coupled documents ----
	sb.WriteString("\n## Most Coupled Documents\n\n")
	sb.WriteString(fmt.Sprintf("Top %d documents by weighted degree across all indexed files (hubs and non-hubs).\n\n", reportTopCoupled))
	coupled := append([]docRow(nil), rows...)
	sort.Slice(coupled, func(i, j int) bool {
		if coupled[i].Weighted != coupled[j].Weighted {
			return coupled[i].Weighted > coupled[j].Weighted
		}
		return coupled[i].Path < coupled[j].Path
	})
	if len(coupled) > reportTopCoupled {
		coupled = coupled[:reportTopCoupled]
	}
	if len(coupled) == 0 {
		sb.WriteString("_No documents indexed in this snapshot._\n")
	} else {
		sb.WriteString("| Document | Degree | Weighted | Hub |\n")
		sb.WriteString("| --- | ---: | ---: | --- |\n")
		for _, r := range coupled {
			hub := ""
			if r.IsHub {
				hub = "yes"
			}
			sb.WriteString(fmt.Sprintf("| `%s` | %d | %.2f | %s |\n", r.Path, r.Degree, r.Weighted, hub))
		}
	}

	// ---- clusters ----
	sb.WriteString("\n## Clusters\n\n")
	sb.WriteString("Documents grouped into higher-level subsystems. Clusters are derived by directory tree, Go module, or network coupling.\n\n")
	if len(graph.Clusters) == 0 {
		sb.WriteString("_No clusters in this snapshot. Rebuild with a recent `kg build`._\n")
	} else {
		byKind := make(map[string][]ir.Cluster)
		for _, c := range graph.Clusters {
			byKind[c.Kind] = append(byKind[c.Kind], c)
		}
		kinds := make([]string, 0, len(byKind))
		for k := range byKind {
			kinds = append(kinds, k)
		}
		sort.Strings(kinds)

		kindLabel := map[string]string{
			ir.ClusterKindDirectory: "directory",
			ir.ClusterKindModule:    "module",
			ir.ClusterKindNetwork:   "network",
		}
		for _, kind := range kinds {
			clusters := byKind[kind]
			sort.Slice(clusters, func(i, j int) bool {
				if clusters[i].Size != clusters[j].Size {
					return clusters[i].Size > clusters[j].Size
				}
				return clusters[i].Name < clusters[j].Name
			})
			sb.WriteString(fmt.Sprintf("### %s\n\n", kindLabel[kind]))
			sb.WriteString("| Cluster | Size | Member preview |\n")
			sb.WriteString("| --- | ---: | --- |\n")
			for _, c := range clusters {
				preview := make([]string, 0, reportMemberPreview)
				for _, m := range c.Members {
					if len(preview) == reportMemberPreview {
						break
					}
					preview = append(preview, "`"+m+"`")
				}
				if len(c.Members) > reportMemberPreview {
					preview = append(preview, fmt.Sprintf("…%d more", len(c.Members)-reportMemberPreview))
				}
				sb.WriteString(fmt.Sprintf("| `%s` | %d | %s |\n", c.Name, c.Size, strings.Join(preview, ", ")))
			}
			sb.WriteString("\n")
		}
	}

	// ---- footer ----
	sb.WriteString("## Notes\n\n")
	sb.WriteString("- Generated with go-graphed `kg visualize`; refresh with `kg build . && kg visualize`.\n")
	sb.WriteString("- Open `graph.html` for an interactive view: drag to pan, scroll to zoom, click a node for details.\n")
	sb.WriteString("- Edges carry provenance: `extracted` links are parsed directly from source; `inferred` links are heuristic.\n")

	return sb.String()
}
